// Builds the composition HTML for one output format. Run `node build.mjs` after editing.
// All copy comes from the live website, so nothing here needs separate sign-off.

export const FORMATS = {
  landscape: { width: 1920, height: 1080 },
  square: { width: 1080, height: 1080 },
  vertical: { width: 1080, height: 1920 },
}

export const DURATION = 25

// Logo ring geometry — identical to components/LogoRings.tsx on the site
const RINGS = [
  { key: 'purple', cx: 64, cy: 107.5, color: '#6d3fe6' },
  { key: 'blue', cx: 143, cy: 107.5, color: '#5b8aa6' },
  { key: 'teal', cx: 103, cy: 177, color: '#3da99c' },
]
const R = 32
const CIRC = +(2 * Math.PI * R).toFixed(2)

const ICONS = {
  wrench:
    '<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.106-3.105c.32-.322.863-.22.983.218a6 6 0 0 1-8.259 7.057l-7.91 7.91a1 1 0 0 1-2.999-3l7.91-7.91a6 6 0 0 1 7.057-8.259c.438.12.54.662.219.984z"/>',
  database:
    '<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5V19A9 3 0 0 0 21 19V5"/><path d="M3 12A9 3 0 0 0 21 12"/>',
  clipboard:
    '<rect width="8" height="4" x="8" y="2" rx="1" ry="1"/><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><path d="m9 14 2 2 4-4"/>',
}

const PILLARS = [
  { name: 'Technical Solutions', icon: 'wrench', services: ['Safe systems of work', 'Authorising engineer', 'Water & ventilation systems'] },
  { name: 'Asset Management', icon: 'database', services: ['Asset validation & capture', 'Condition surveys', 'Lifecycle planning'] },
  { name: 'Compliance Management', icon: 'clipboard', services: ['Compliance audits', 'Gap analysis', 'Regulatory reporting'] },
]

const rings = (cls, { hairline = false, orbits = false, width = 4.5 } = {}) => `
  <svg class="${cls}" viewBox="26 70 156 146" fill="none" overflow="visible">
    ${RINGS.map(
      (r) => `
    <g class="ring-group ring-group-${r.key}">
      ${orbits ? `<circle class="orbit orbit-${r.key}" cx="${r.cx}" cy="${r.cy}" r="${R + 7}" stroke="${r.color}" stroke-width="${width * 0.6}" stroke-dasharray="1 5" stroke-linecap="round" opacity="0.55"${hairline ? ' vector-effect="non-scaling-stroke"' : ''}/>` : ''}
      <circle class="ring ring-${r.key}" cx="${r.cx}" cy="${r.cy}" r="${R}" stroke="${r.color}" stroke-width="${width}" stroke-linecap="round" stroke-dasharray="${CIRC}" transform="rotate(-90 ${r.cx} ${r.cy})"${hairline ? ' vector-effect="non-scaling-stroke"' : ''}/>
    </g>`
    ).join('')}
  </svg>`

const lockup = (cls) => `
  <div class="lockup ${cls}">
    ${rings('lockup-rings')}
    <img class="lockup-wordmark" src="assets/logo-wordmark.webp" alt="RPW Technical Consulting (FM) Ltd" />
  </div>`

const scene = (id, start, end, inner, extra = '') =>
  `<section id="${id}" class="clip scene ${extra}" data-start="${start}" data-duration="${+(end - start).toFixed(2)}">${inner}</section>`

export function render(format, { css, js }) {
  const { width, height } = FORMATS[format]
  return `<!doctype html>
<!-- GENERATED by "node build.mjs ${format}" from src/ — edit the source, not this file -->
<html lang="en-GB">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=${width}, height=${height}" />
    <style>
${css}
    </style>
    <script src="assets/gsap.min.js"></script>
  </head>
  <body class="fmt-${format}" style="width:${width}px;height:${height}px">
    <div id="root" data-composition-id="main" data-start="0" data-duration="${DURATION}" data-width="${width}" data-height="${height}">

      <!-- Persistent background: gradient, technical grid, faint orbiting rings -->
      <div id="bg" class="clip" data-start="0" data-duration="${DURATION}">
        <div class="bg-glow"></div>
        <div class="bg-grid"></div>
        ${rings('bg-rings', { hairline: true, orbits: true, width: 1.5 })}
      </div>

      ${scene('s-logo', 0, 3.8, lockup('logo-main'))}

      ${scene(
        's-headline',
        3.6,
        7.7,
        `<h1 class="headline">
          <span class="line"><span class="line-inner">Technical assurance</span></span>
          <span class="line"><span class="line-inner">that holds up under</span></span>
          <span class="line"><span class="line-inner accent">inspection.</span></span>
        </h1>
        <div class="tag"><span class="dot"></span>North-East England · Remote &amp; On-Site</div>`
      )}

      ${scene(
        's-pillars',
        7.5,
        13.6,
        `<p class="eyebrow">${rings('eyebrow-rings', { width: 9 })}<span>What we do</span></p>
        <h2 class="title"><span class="line"><span class="line-inner">Three pillars. One specialist.</span></span></h2>
        <div class="cards">
          ${PILLARS.map(
            (p, i) => `
          <div class="card card-${i}">
            <span class="card-accent"></span>
            <div class="card-head">
              <span class="card-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${ICONS[p.icon]}</svg></span>
              <span class="card-num">0${i + 1}</span>
            </div>
            <h3>${p.name}</h3>
            <ul>${p.services.map((s) => `<li>${s}</li>`).join('')}</ul>
          </div>`
          ).join('')}
        </div>`
      )}

      ${scene(
        's-independent',
        13.4,
        18.1,
        `<h2 class="big"><span class="line"><span class="line-inner">Independent.</span></span></h2>
        <p class="sub"><span class="line"><span class="line-inner">No vendor ties. Advice that serves your interests.</span></span></p>
        <div class="rule"></div>
        <ul class="sectors">
          <li>Healthcare &amp; NHS</li><li class="sep">·</li><li>Public sector</li><li class="sep">·</li><li>Complex infrastructure</li>
        </ul>`
      )}

      ${scene(
        's-richard',
        17.9,
        22.2,
        `<div class="portrait">
          <img src="assets/richard-portrait.jpg" alt="Richard Warren" />
          <div class="portrait-cover"></div>
          ${rings('portrait-rings', { hairline: true, width: 1.5 })}
        </div>
        <div class="bio">
          <p class="eyebrow">${rings('eyebrow-rings', { width: 9 })}<span>Led by</span></p>
          <h2 class="name"><span class="line"><span class="line-inner">Richard Warren</span></span></h2>
          <p class="role">Principal Consultant</p>
          <p class="bio-line">Decades of estates leadership across healthcare, public sector and complex infrastructure.</p>
        </div>`
      )}

      ${scene(
        's-close',
        22,
        DURATION,
        `${lockup('logo-close')}
        <div class="close-lines">
          <p class="cta">Start a conversation</p>
          <p class="url">rpwtechnicalconsulting.co.uk</p>
          <p class="linkedin"><span class="in">in</span>Find Richard Warren on LinkedIn</p>
        </div>`
      )}
    </div>
    <script>
${js}
    </script>
  </body>
</html>
`
}
